name: Build for package managers

on:
  push:
    paths-ignore:
      - ".gitignore"
      - ".gitattributes"
      - "**.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - ".gitignore"
      - ".gitattributes"
      - "**.md"
      - "LICENSE"
  workflow_dispatch:

env:
  CONTAINER_COMMAND: "podman run
                        --platform $PLATFORM
                        --rm
                        --security-opt seccomp=unconfined
                        --volume $PWD:/mnt
                        --workdir /mnt
                        $IMAGE"

# order by: alphabet
jobs:
  alpine:
    name: Alpine Linux
    runs-on: ubuntu-latest
    env:
      IMAGE: docker.io/amd64/alpine:edge
      PLATFORM: linux/amd64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          ${{ env.CONTAINER_COMMAND }} ./packages/alpine/01-in-docker.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Alpine Linux
          path: dist/*.apk

  archlinux:
    name: Arch Linux
    runs-on: ubuntu-latest
    env:
      IMAGE: docker.io/amd64/archlinux:latest
      PLATFORM: linux/amd64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          ${{ env.CONTAINER_COMMAND }} ./packages/archlinux/01-in-docker.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Arch Linux
          path: dist/*.pkg.tar.zst

  archlinux_hwcaps:
    name: Arch Linux (glibc hwcaps)
    runs-on: ubuntu-latest
    env:
      IMAGE: docker.io/amd64/archlinux:latest
      PLATFORM: linux/amd64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          ${{ env.CONTAINER_COMMAND }} ./packages/archlinux-hwcaps/01-in-docker.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Arch Linux (glibc hwcaps)
          path: dist/*.pkg.tar.zst

  brew:
    name: Homebrew
    strategy:
      fail-fast: false
      matrix:
        os: [Linux, "macOS 26", "macOS 15", "macOS 14"]
        arch: [x86_64, arm64]
        include:
          - { os: Linux, arch: x86_64, runner: ubuntu-24.04 }
          - { os: Linux, arch: arm64, runner: ubuntu-24.04-arm }
          - { os: "macOS 26", arch: x86_64, runner: macos-26-intel }
          - { os: "macOS 26", arch: arm64, runner: macos-26 }
          - { os: "macOS 15", arch: x86_64, runner: macos-15-intel }
          - { os: "macOS 15", arch: arm64, runner: macos-15 }
          - { os: "macOS 14", arch: arm64, runner: macos-14 }
        exclude:
          - { os: "macOS 14", arch: x86_64 }  # no standard runner
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Homebrew
        if: ${{ matrix.os == 'Linux' }}
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Build
        run: |
          if [[ "${{ matrix.os }}" == Linux ]] ; then
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          fi
          brew tap --force homebrew/core
          ./packages/brew/buildbottle.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Homebrew ${{ matrix.os }} ${{ matrix.arch }}
          path: dist/*.bottle.tar.gz

  debian:
    name: Debian
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, i386]
        include:
          - { arch: amd64, platform: linux/amd64 }
          - { arch: i386, platform: linux/386 }
    env:
      IMAGE: docker.io/${{ matrix.arch }}/debian:testing
      PLATFORM: ${{ matrix.platform }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          ${{ env.CONTAINER_COMMAND }} ./packages/debian/01-in-docker.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Debian testing ${{ matrix.arch }}
          path: dist/*.deb

  fedora:
    name: Fedora
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["latest", "rawhide"]
    env:
      IMAGE: docker.io/amd64/fedora:${{ matrix.version }}
      PLATFORM: linux/amd64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          ${{ env.CONTAINER_COMMAND }} ./packages/fedora/01-in-docker.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Fedora ${{ matrix.version }} x86_64
          path: dist/*.rpm

  msys2:
    name: MSYS2
    strategy:
      fail-fast: false
      matrix:
        msystem: [MINGW64, UCRT64, CLANG64, CLANGARM64]
        include:
          - { msystem: MINGW64, runner: windows-2022 }
          - { msystem: UCRT64, runner: windows-2022 }
          - { msystem: CLANG64, runner: windows-2022 }
          - { msystem: CLANGARM64, runner: windows-11-arm }
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: base-devel git

      - name: Build
        run: |
          ./packages/msys/buildpkg.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: MSYS2 ${{ matrix.msystem }}
          path: dist/

  opensuse:
    name: openSUSE
    runs-on: ubuntu-latest
    env:
      IMAGE: docker.io/opensuse/tumbleweed:latest
      PLATFORM: linux/amd64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          ${{ env.CONTAINER_COMMAND }} ./packages/opensuse/01-in-docker.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: openSUSE Tumbleweed x86_64
          path: dist/*.rpm

  ubuntu:
    name: Ubuntu
    env:
      IMAGE: docker.io/amd64/ubuntu:devel
      PLATFORM: linux/amd64

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          ${{ env.CONTAINER_COMMAND }} ./packages/debian/01-in-docker.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Ubuntu devel amd64
          path: dist/*.deb
